-- New script in WISE_STAGING(142).
-- Date: Dec 2, 2023
-- Time: 12:29:38 PM
-- DB LINK MOBILE_SURVEY
 

select * from information_schema.tables where TABLE_CATALOG ='WOMFMSS'

select top 10 * From FINAL_TR_TASK_H order by SUBMIT_DATE desc

SELECT top 100 mf.FORM_NAME, tth.APPL_NO,tth.STATUS_MOBILE_SEQ_NO,am.login_id,am.full_name,mj.DESCRIPTION,tth.ORDER_NO_CAE,* FROM WOMFMSS.dbo.TR_TASK_H tth WITH (NOLOCK)
left JOIN WOMFMSS.dbo.MS_FORM mf ON tth.UUID_FORM = mf.UUID_FORM
left JOIN WOMFMSS.dbo.AM_MSUSER am ON tth.UUID_MS_USER = am.UUID_MS_USER
left JOIN WOMFMSS.dbo.MS_JOB mj ON am.UUID_JOB = mj.UUID_JOB
WHERE appl_no IN ('ODRNO2407050003') --POL000797377

 

SELECT
	TH.UUID_TASK_H,TH.dtm_CRT , TH.USR_CRT, TH.APPL_NO, TH.AUTO_PRESURVEY, th.CUSTOMER_NAME ,
	ST.STATUS_TASK_DESC,
	TH.ORDER_NO_CAE, 
	TH.IS_PRE_APPROVAL, TH.OPSI_PENANGANAN, STATUS_FOLLOW_UP,
	MF.FORM_NAME,
	TH.SUBZIPCODE, mb.BRANCH_NAME , 
	AMS.LOGIN_ID , ams.FULL_NAME ,th.UUID_MS_USER 
--	into #tempData
FROM WOMFMSS.dbo.TR_TASK_H TH WITH(NOLOCK)
left JOIN WOMFMSS..MS_STATUSTASK ST WITH(NOLOCK) ON TH.UUID_STATUS_TASK = ST.UUID_STATUS_TASK
left JOIN WOMFMSS..MS_FORM  MF WITH(NOLOCK) ON MF.UUID_FORM = TH.UUID_FORM
left JOIN WOMFMSS.dbo.MS_BRANCH MB WITH(NOLOCK) ON MB.UUID_BRANCH = TH.UUID_BRANCH
left JOIN WOMFMSS.dbo.AM_MSUSER AMS WITH(NOLOCK) ON AMS.UUID_MS_USER = TH.UUID_MS_USER
LEFT JOIN WOMFMSS..AM_MSUSER SPV WITH(NOLOCK) ON SPV.UUID_MS_USER = AMS.SPV_ID  
WHERE
--th.UUID_TASK_H ='5834766'
TH.APPL_NO in ('ODRNO2408260013') 
order by th.DTM_CRT  desc


SELECT * FROM ms_job


select QUESTION_TEXT , TEXT_ANSWER ,INT_TEXT_ANSWER   from TR_TASK_D ttd where ttd.UUID_TASK_H =5020306

or
ISNULL(ISNULL(TH.ORDER_NO_CAE,TH.TASK_ID_POLO),TH.APPL_NO) in ('POL000795679 ','POL000795681 ','ODRNO2401020004') 

select 
'Prospek' "Result"
,tmp.* 
from #tempData tmp
order by order_no_cae asc


SELECT TH.TASK_ID ,
	TH.UUID_TASK_H, TH.USR_CRT, TH.DTM_CRT,TH.APPL_NO, TH.ORDER_NO_CAE,  --TH.UUID_MS_USER, TH.UUID_BRANCH, TH.UUID_FORM, TH.UUID_STATUS_TASK, TH.UUID_PRIORITY, 
	TH.AUTO_PRESURVEY,TH.MANDATORY_LEVEL, TH.IS_PRE_APPROVAL, TH.OPSI_PENANGANAN,
	ST.IS_ACTIVE, ST.STATUS_TASK_DESC, ST.IS_FLAGSTATUSFINAL,
	TH.CUSTOMER_NAME, TH.SUBZIPCODE, TH.NOTES,
	MF.FORM_NAME,
	MB.BRANCH_CODE, MB.BRANCH_NAME,
	AMS.LOGIN_ID, AMS.FULL_NAME, AMS.IS_LOGGED_IN, AMS.IS_ACTIVE AS IS_ACTIVE_AMS ,AMS.UNIQUE_ID, AMS.SPV_ID,
	SPV.LOGIN_ID AS LOGIN_ID_SPV, SPV.FULL_NAME AS FULL_NAME_SPV,  SPV.IS_LOGGED_IN AS IS_LOGGED_IN_SPV, SPV.IS_ACTIVE AS IS_ACTIVE_SPV, SPV.UNIQUE_ID AS UNIQUE_ID_SPV
	,th.USR_UPD , th.DTM_UPD , th.START_DTM , th.NOTES_CRM , th.MAX_RETRY 
--	into #data
FROM WOMFMSS.dbo.TR_TASK_H TH WITH(NOLOCK)
left JOIN WOMFMSS.dbo.MS_STATUSTASK ST WITH(NOLOCK) ON TH.UUID_STATUS_TASK = ST.UUID_STATUS_TASK
left JOIN WOMFMSS.dbo.MS_FORM  MF WITH(NOLOCK) ON MF.UUID_FORM = TH.UUID_FORM
left JOIN WOMFMSS.dbo.MS_BRANCH MB WITH(NOLOCK) ON MB.UUID_BRANCH = TH.UUID_BRANCH
left JOIN WOMFMSS.dbo.AM_MSUSER AMS WITH(NOLOCK) ON AMS.UUID_MS_USER = TH.UUID_MS_USER
LEFT JOIN WOMFMSS.dbo.AM_MSUSER SPV WITH(NOLOCK) ON SPV.UUID_MS_USER = AMS.SPV_ID 
WHERE 1=1
and th.ORDER_NO_CAE  ='POL000910933'--'POL000797388' 
--th.APPL_NO ='ODRNO2402160033'
--ISNULL(TH.ORDER_NO_CAE,TH.TASK_ID_POLO) = 'POL000795958 '

and TH.USR_CRT like '%Add Task Scoring CAE%'
and ST.STATUS_TASK_DESC not like '%Release%'
and ST.STATUS_TASK_DESC not like '%Reject%'
and ST.STATUS_TASK_DESC not like '%Delete%'
and ST.STATUS_TASK_DESC like '%Approval on WOM%'

select * from TR_TASK_H tth where tth.UUID_TASK_H =5044445

select TASK_ID , APPL_NO , USR_CRT , STATUS_TASK_DESC , FORM_NAME , LOGIN_ID, FULL_NAME From #data

select MAX_RETRY  from TR_TASK_H tth  where ORDER_NO_CAE ='POL000909476'

select * from WOMFMSS.dbo.STAGING_PRODUCT_OFFERING spo where PRODUCT_OFFERING_CODE ='OFFOFFMTRKUK'



ODRNO2401200003
POL000795955

select USR_CRT , DTM_CRT , APPL_NO , OPSI_PENANGANAN , CUSTOMER_NAME , STATUS_FOLLOW_UP , TASK_ID_POLO , ORDER_NO_CAE 
from WOMFMSS.dbo.TR_TASK_H tth 
where tth.UUID_TASK_H =5020026

select * from TR_TASK_D ttd where ttd.UUID_TASK_H ='POL000795782'

th.APPL_NO='ODRNO2312270003'

ISNULL(TH.ORDER_NO_CAE,TH.TASK_ID_POLO) = 'POL000795572'

ODRNO2312270003

select top 100 * from TBL_CAE_DATA tcd where ORDER_NO_CAE = 'POL000909353' order by dtm_crt desc

select top 100 * from TBL_POLO_DATA tpd order by DTM_CRT desc


SELECT mb.BRANCH_NAME FROM AM_MSUSER am 
JOIN MS_BRANCH mb ON am.UUID_BRANCH =mb.UUID_BRANCH 
WHERE am.LOGIN_ID LIKE '%DOCU%'
AND am.IS_ACTIVE =1
AND mb.BRANCH_NAME  LIKE '%YOGY%'

SELECT * FROM am_msuser WHERE UUID_MS_USER ='54184'

SELECT * FROM ms_branch
WHERE BRANCH_NAME  LIKE '%YOGYA%'--387

select * FROM WOMFMSS..TR_TASK_H TH 
ODRNO2312270003

--cekk mss
SELECT --top 100 --AMS.*
AMS.IS_ACTIVE, AMS.LOGIN_ID, AMS.FULL_NAME, AMS.UNIQUE_ID, AMS.IS_LOGGED_IN, AMS.IS_LOCKED, --ams.PASSWORD,
MB.BRANCH_CODE, MB.BRANCH_NAME, MB.IS_PILOTING, MB.IS_PILOTING_CAE,
SPV.FULL_NAME AS FULL_NAME_SPV, SPV.IS_ACTIVE AS IS_ACTIVE_SPV, SPV.UNIQUE_ID
FROM WOMFMSS..AM_MSUSER AMS WITH(NOLOCK) 
JOIN WOMFMSS..MS_BRANCH MB WITH(NOLOCK) ON MB.UUID_BRANCH = AMS.UUID_BRANCH
LEFT JOIN WOMFMSS..AM_MSUSER SPV WITH(NOLOCK) ON SPV.UUID_MS_USER = AMS.SPV_ID
WHERE
AMS.IS_ACTIVE IN ('1')
AND MB.BRANCH_NAME  like 'H0725'
and ams.login_id like '%CS'
--and ams.login_id='000222275_5311_CS'
--AND AMS.FULL_NAME LIKE '%ETIKA VIRDA PRATAMA%'


SELECT *
FROM WOMFMSS..AM_MSUSER AMS WITH(NOLOCK) 
JOIN WOMFMSS..MS_BRANCH MB WITH(NOLOCK) ON MB.UUID_BRANCH = AMS.UUID_BRANCH
LEFT JOIN WOMFMSS..AM_MSUSER SPV WITH(NOLOCK) ON SPV.UUID_MS_USER = AMS.SPV_ID
WHERE
AMS.IS_ACTIVE IN ('1')
--AND MB.BRANCH_NAME  like 'MAKASAR'
AND AMS.FULL_NAME='NURJEN'


select * FROM WOMFMSS..AM_MSUSER AMS WITH(NOLOCK) where full_name like '%MIFTA%'


select * from information_schema.tables where table_name like '%user%'

select * from AM_MSUSER where UNIQUE_ID ='149203521'

select * from AM_MSUSER am  where LOGIN_ID ='076232411_0221_FL'

select * from AM_MSUSER where LOGIN_ID  like '%FL%' and UUID_BRANCH =302

select * from TBL_PRODUCT_CATEGORY where product_category_code='MGJMTRKON'

select * from MS_MAPPING_USER_KAT kat  where USERNAME like '%FL%' and IS_ACTIVE =1 and USERNAME !='068111350_5641_CS'


select * from WOMFMSS.dbo.MS_MAPPING_USER_KAT mmuk where id='7181052'

update kat set IS_ACTIVE =1 from MS_MAPPING_USER_KAT kat where id = 7181052

select UUID_MS_USER , IS_ACTIVE , FULL_NAME , LOGIN_ID , SPV_ID, IS_LOGGED_IN, *  from AM_MSUSER where LOGIN_ID like '058231196_0231_CMO'

update a set is_active=1, IS_LOGGED_IN =0 from AM_MSUSER a where LOGIN_ID ='14508016_1491_BH'

select IS_ACTIVE , FULL_NAME , LOGIN_ID , SPV_ID  from AM_MSUSER where UNIQUE_ID  ='447220196'

select * from TR_TASK_H tth  where tth.UUID_MS_USER  =202733

select * from TR_TASK_H tth  where TASK_ID_POLO ='POL000795782'

select * from MS_GROUPTASK mg where mg.UUID_TASK_H =4999777

select * from TR_TASK_D ttd  where ttd.UUID_TASK_H =4999777

select * from TR_TASKHISTORY tt where tt.UUID_TASK_H =4999777

select * from WF_EVENT we where we.UUID_TASK_H =4999777

select * from TBL_POLO_DATA tpd where TASK_ID_POLO ='POL000795572'

select UNIQUE_ID   from AM_MSUSER where LOGIN_ID  like '%FL%' and UUID_BRANCH =302 and IS_ACTIVE =1

select * from #uniqueid

select kat.* --, am.LOGIN_ID , am.FULL_NAME , am.IS_LOCKED , am.FAIL_COUNT , am.IS_ACTIVE user_active , am.IS_DELETED , am.IS_LOGGED_IN , am.USR_UPD , am.DTM_UPD  
--into #temp
from MS_MAPPING_USER_KAT kat 
join TBL_PRODUCT_CATEGORY tpc on tpc.TBL_PRODUCT_CATEGORY_ID  =kat.TBL_PRODUCT_CATEGORY_ID 
join MS_LOV ml on ml.CODE =kat.KAT_CODE 
join AM_MSUSER am on am.LOGIN_ID = kat.USERNAME  
where kat.IS_ACTIVE=1
--and am.IS_ACTIVE =1
--and kat.USERNAME like '%CRO'
and tpc.PRODUCT_CATEGORY_CODE ='MDLMBL'

and kat.KAT_CODE in ('E7202')

select KAT_CODE , count(1) from #temp where IS_ACTIVE =1 group by KAT_CODE 

select RIGHT(kat.USERNAME,3)_ROLE, am.UUID_MS_USER , mb.BRANCH_CODE , mb.BRANCH_NAME , kat.KAT_CODE 
, kat.IS_ACTIVE KAT_ACTIVE, am.IS_ACTIVE USER_ACTIVE 
, am.IS_LOGGED_IN 
, COUNT(1) TOTAL  
from MS_MAPPING_USER_KAT kat 
join TBL_PRODUCT_CATEGORY tpc on tpc.TBL_PRODUCT_CATEGORY_ID  =kat.TBL_PRODUCT_CATEGORY_ID 
join MS_LOV ml on ml.CODE =kat.KAT_CODE 
join AM_MSUSER am on am.LOGIN_ID = kat.USERNAME  
left join MS_BRANCH mb on mb.UUID_BRANCH =kat.UUID_BRANCH 
where kat.IS_ACTIVE=kat.IS_ACTIVE
and kat.USERNAME like '%_%_BCMH%'
and tpc.PRODUCT_CATEGORY_CODE ='MGBMTRKON'
and kat.KAT_CODE in ('H0086')
GROUP BY RIGHT(kat.USERNAME,3),am.UUID_MS_USER, mb.BRANCH_CODE , mb.BRANCH_NAME , kat.KAT_CODE , kat.IS_ACTIVE, am.IS_ACTIVE ,am.IS_LOGGED_IN 
order by kat.KAT_CODE,kat.IS_ACTIVE desc

SELECT COL_NAME, tbl.REF_ID, msa.CODE_ANSWER_TYPE, IS_MANDATORY
			FROM   TBL_MAP_TASK_D tbl WITH(NOLOCK)
			JOIN   MS_FORMQUESTIONSET msq WITH(NOLOCK) on msq.REF_ID = tbl.REF_ID and msq.UUID_FORM_HISTORY = (SELECT MAX(mf.UUID_FORM_HISTORY) FROM MS_FORMHISTORY mf
				WITH(NOLOCK) WHERE mf.UUID_FORM = (SELECT mf1.UUID_FORM FROM MS_FORM mf1 WITH(NOLOCK) WHERE mf1.FORM_NAME = 'Form Pre Survey'))
			JOIN   MS_ANSWERTYPE msa WITH (NOLOCK) on msa.UUID_ANSWER_TYPE = msq.UUID_ANSWER_TYPE 
			WHERE  tbl.UUID_FORM = (SELECT mf1.UUID_FORM FROM MS_FORM mf1 WITH(NOLOCK) WHERE mf1.FORM_NAME = 'Form Pre Survey')
--			       AND msq.IS_MANDATORY�=�'1'
			       and col_name like '%foto%'

			       select * From TBL_PRODUCT_CATEGORY
			       
			       select * from AM_ATTRIBUTEOFMEMBER where USR_CRT ='928'
			       
			       select * from AM_MSATTRIBUTE
			       
			       select * from AM_MSUSER am where UUID_JOB = 9 and IS_ACTIVE =1 and UNIQUE_ID ='428220838' and UUID_BRANCH = 445
			       
			       select LOGIN_ID , FULL_NAME , am.UUID_BRANCH   , mb.BRANCH_CODE , mb.BRANCH_NAME , am.IS_ACTIVE 
			       from AM_MSUSER am 
			       join MS_BRANCH mb on am.UUID_BRANCH = mb.UUID_BRANCH 
			       where UUID_JOB = 9  and UNIQUE_ID ='114233135'
			       
			       select * from MS_BRANCH where branch_code ='2091'-- 445
			       
			       --114233135_4411_CMO   058231196_0231_CMO
			        
			       select * from MS_JOB where JOB_CODE ='CMO' --9
			       
			       select * from MS_MAPPING_USER_KAT where IS_ACTIVE =1 and TBL_PRODUCT_CATEGORY_ID =5 and KAT_CODE ='H0479' and USERNAME ='428220838_5661_CMO'
			       
			       select * from MS_MAPPING_USER_KAT where  USERNAME ='428220838_5661_CMO'
			       
 --Assign Task by KAT
 SELECT distinct MMUK.TBL_PRODUCT_CATEGORY_ID , msb.IS_PILOTING_CAE, msb.IS_PILOTING, mj.JOB_CODE  , amm.IS_ACTIVE  USER_ACTIVE, mmuk.IS_ACTIVE KAT_ACTIVE
 ,mmuk.KAT_CODE , msb.BRANCH_CODE , msb.BRANCH_NAME , tpc.PRODUCT_CATEGORY_CODE , tpc.PRODUCT_CATEGORY_NAME 
 , AMAOM.UUID_MS_USER MEMBER_ID, AMM.UUID_MS_USER, AMM.UNIQUE_ID , amm.FULL_NAME 
 , MMUK.* 
 , spv.LOGIN_ID LOGIN_SPV, spv.FULL_NAME SPV_NAME
-- INTO #TEMP 
 
 select amm.FULL_NAME ,MMUK.* 
 FROM MS_MAPPING_USER_KAT MMUK WITH (NOLOCK) 
 JOIN AM_MSUSER AMM WITH (NOLOCK) ON AMM.LOGIN_ID = MMUK.USERNAME 
 left JOIN MS_JOB MJ WITH(NOLOCK) ON MJ.UUID_JOB = AMM.UUID_JOB --
 left JOIN MS_BRANCH MSB WITH (NOLOCK) ON MSB.UUID_BRANCH = AMM.UUID_BRANCH  AND MSB.IS_PILOTING_CAE = '1' 
 left JOIN AM_ATTRIBUTEOFMEMBER AMAOM WITH (NOLOCK) ON AMAOM.UUID_MS_USER = AMM.UUID_MS_USER 
 left JOIN AM_MSATTRIBUTE AMMA WITH (NOLOCK) ON AMMA.UUID_MS_ATTRIBUTE = AMAOM.UUID_MS_ATTRIBUTE 
 left join TBL_PRODUCT_CATEGORY tpc on tpc.TBL_PRODUCT_CATEGORY_ID =mmuk.TBL_PRODUCT_CATEGORY_ID 
 left JOIN WOMFMSS.dbo.AM_MSUSER AMS WITH(NOLOCK) ON AMS.UUID_MS_USER = MMUK.USERNAME 
 left JOIN WOMFMSS.dbo.AM_MSUSER SPV WITH(NOLOCK) ON SPV.UUID_MS_USER = AMS.SPV_ID 
 WHERE MSB.UUID_BRANCH =MSB.UUID_BRANCH
-- AND MMUK.KAT_CODE = 'G5184'-- MMUK.KAT_CODE--'H0479'
	AND MMUK.IS_ACTIVE = '1' 
	AND AMM.IS_ACTIVE = '1' 
	and MSB.branch_name ='BEKASI'
-- 	AND MJ.JOB_CODE = 'FL' 
--	AND MMUK.TBL_PRODUCT_CATEGORY_ID = '5' 
 	and tpc.PRODUCT_CATEGORY_CODE ='MGBMTRKON'
--	AND MSB.KONVEN_SYARIAH = 'KONVENSIONAL' 	
-- and amm.UNIQUE_ID in (select * from  #uniqueid)
	AND ISNULL(MSB.IS_PILOTING,'0')=1
--	and MMUK.USERNAME in ('030100461_0191','286223415_0111_CMO')
	

	030100461_0191
	
	select * from MS_MAPPING_USER_KAT mmuk where mmuk.ID =7925

 	

select DISTINCT UNIQUE_ID from #TEMP
	
	 
select * from AM_MSUSER am where LOGIN_ID  in ('156231307_2091_CMO','00008001_0191_BH','000170386_0201_BH') 
 
000223888_0071_BCMH atau 026230122_0071_BH

select * from MS_BRANCH mb where mb.BRANCH_NAME ='DAAN MOGOT'

select * From AM_MSUSER where AM_MSUSER.LOGIN_ID like '%_0071_%BH%' and IS_ACTIVE =1

select mmuk.* 
from MS_MAPPING_USER_KAT  MMUK
JOIN AM_MSUSER AMM WITH (NOLOCK) ON AMM.LOGIN_ID = MMUK.USERNAME 
where kat_code='H0479' 
and  TBL_PRODUCT_CATEGORY_ID =5 
and MMUK.IS_ACTIVE =1
and amm.IS_ACTIVE =1
and USERNAME like '%CMO%'

select mmuk.* 
from MS_MAPPING_USER_KAT  MMUK
where USERNAME ='447222966_5311_CRO'
and kat_code='E5656' 

and  TBL_PRODUCT_CATEGORY_ID =5 

select * from TBL_PRODUCT_CATEGORY tpc where PRODUCT_CATEGORY_CODE ='MGJMBLKON'

select * from TR_TASK_H tth  where  UUID_MS_USER =202733 

 SELECT mb.BRANCH_CODE,mb.BRANCH_NAME , LOGIN_ID 
 FROM AM_MSUSER AMU WITH(NOLOCK)
 JOIN MS_BRANCH mb WITH(NOLOCK) ON AMU.UUID_BRANCH = mb.UUID_BRANCH  
 JOIN MS_JOB MSJ WITH(NOLOCK) ON MSJ.UUID_JOB = AMU.UUID_JOB  
 WHERE JOB_CODE = 'FL' 
	AND UNIQUE_ID = '076232411' 
	AND AMU.IS_ACTIVE='1'  
--	AND mb.BRANCH_CODE�=�'5761'

	
	
SELECT *
FROM TR_TASK_H tth WITH(NOLOCK)
WHERE 1=1
AND OPSI_PENANGANAN = 'Di Cabang'
ORDER BY DTM_CRT DESC

--Di Rumah
--Di Cabang
'Di�Cabang'
SELECT ASCII(' ')
SELECT ASCII(' ')

--mss
SELECT *
FROM TR_TASK_H tth WITH(NOLOCK)
WHERE OPSI_PENANGANAN = 'Di Cabang'
ORDER BY DTM_CRT DESC

select * from TBL_MAP_TASK_D where COL_NAME  like '%img%'

SELECT COL_NAME, tbl.REF_ID, msa.CODE_ANSWER_TYPE,  msq.IS_MANDATORY
FROM   TBL_MAP_TASK_D tbl WITH(NOLOCK)
JOIN   MS_FORMQUESTIONSET msq WITH(NOLOCK) on msq.REF_ID = tbl.REF_ID and msq.UUID_FORM_HISTORY = (SELECT MAX(mf.UUID_FORM_HISTORY) FROM MS_FORMHISTORY mf WITH(NOLOCK) WHERE mf.UUID_FORM = 55)
JOIN   MS_ANSWERTYPE msa WITH (NOLOCK) on msa.UUID_ANSWER_TYPE = msq.UUID_ANSWER_TYPE
WHERE  tbl.UUID_FORM = 55
--       AND msq.IS_MANDATORY = '0'
       and col_name like '%img%'
ORDER�BY�COL_NAME


select * from TR_TASK_H tth 



select * from TBL_CAE_DATA tcd where tcd.ORDER_NO_CAE ='POL000908995'


select * from STAGING_SURVEYOR_OFFICE

select B.* from STAGING_SURVEYOR_OFFICE A with(nolock)
JOIN AM_MSUSER B WITH(NOLOCK) ON A.USERNAME = B.UNIQUE_ID 
WHERE JOB_TITLE_CODE IN (
'R4000093KC',
'R4000167KC',
'R4000168KC',
'R4000169KC',
'R4000093KP',
'R4000093KP',
'R4000093HO',
'R4000093KS',
'R4000093BU')

 select kat.* , am.IS_ACTIVE 
from MS_MAPPING_USER_KAT kat 
join TBL_PRODUCT_CATEGORY tpc on tpc.TBL_PRODUCT_CATEGORY_ID  =kat.TBL_PRODUCT_CATEGORY_ID 
join MS_LOV ml on ml.CODE =kat.KAT_CODE 
join AM_MSUSER am on am.LOGIN_ID = kat.USERNAME  
left join MS_BRANCH mb on mb.UUID_BRANCH =kat.UUID_BRANCH 
where kat.IS_ACTIVE=kat.IS_ACTIVE
and kat.USERNAME like '%_%_Cro'
and tpc.PRODUCT_CATEGORY_CODE ='MGJMTRKON'
and kat.KAT_CODE = 'E5602' and kat.IS_ACTIVE = 1 

select * from MS_MAPPING_USER_KAT where UUID_BRANCH =441

SELECT TH.TASK_ID ,
	TH.UUID_TASK_H, TH.USR_CRT, TH.DTM_CRT,TH.APPL_NO, TH.ORDER_NO_CAE,
	TH.AUTO_PRESURVEY,TH.MANDATORY_LEVEL, TH.IS_PRE_APPROVAL, TH.OPSI_PENANGANAN,
	ST.IS_ACTIVE, ST.STATUS_TASK_DESC, ST.IS_FLAGSTATUSFINAL,
	TH.CUSTOMER_NAME, TH.SUBZIPCODE, TH.NOTES,
	MF.FORM_NAME,
	MB.BRANCH_CODE, MB.BRANCH_NAME, TH.ORDER_NO_CAE,
	AMS.LOGIN_ID, AMS.FULL_NAME, AMS.IS_LOGGED_IN, AMS.IS_ACTIVE AS IS_ACTIVE_AMS ,AMS.UNIQUE_ID, AMS.SPV_ID,
	SPV.LOGIN_ID AS LOGIN_ID_SPV, SPV.FULL_NAME AS FULL_NAME_SPV,  SPV.IS_LOGGED_IN AS IS_LOGGED_IN_SPV, SPV.IS_ACTIVE AS IS_ACTIVE_SPV, SPV.UNIQUE_ID AS UNIQUE_ID_SPV
FROM WOMFMSS.dbo.TR_TASK_H TH WITH(NOLOCK)
left JOIN WOMFMSS.dbo.MS_STATUSTASK ST WITH(NOLOCK) ON TH.UUID_STATUS_TASK = ST.UUID_STATUS_TASK
left JOIN WOMFMSS.dbo.MS_FORM  MF WITH(NOLOCK) ON MF.UUID_FORM = TH.UUID_FORM
left JOIN WOMFMSS.dbo.MS_BRANCH MB WITH(NOLOCK) ON MB.UUID_BRANCH = TH.UUID_BRANCH
left JOIN WOMFMSS.dbo.AM_MSUSER AMS WITH(NOLOCK) ON AMS.UUID_MS_USER = TH.UUID_MS_USER
LEFT JOIN WOMFMSS.dbo.AM_MSUSER SPV WITH(NOLOCK) ON SPV.UUID_MS_USER = AMS.SPV_ID
WHERE ISNULL(TH.ORDER_NO_CAE,TH.TASK_ID_POLO) = 'POL000909088'

select * from information_schema.routines where routine_name like '%SYNC_SURVEYOR_OFFICE%'


SELECT E.REF_ID, E.IS_MANDATORY, F.RELEVANT_MANDATORY
FROM MS_FORM A with(nolock)
JOIN MS_QUESTIONGROUPOFFORM B with(nolock) ON A.UUID_FORM = B.UUID_FORM
JOIN MS_QUESTIONGROUP C with(nolock) ON B.UUID_QUESTION_GROUP = C.UUID_QUESTION_GROUP
JOIN MS_QUESTIONOFGROUP D with(nolock) ON C.UUID_QUESTION_GROUP = D.UUID_QUESTION_GROUP
JOIN MS_QUESTION E with(nolock) ON D.UUID_QUESTION = E.UUID_QUESTION
LEFT JOIN MS_QUESTIONRELEVANT F with(nolock) ON A.UUID_FORM = F.UUID_FORM AND C.UUID_QUESTION_GROUP = F.UUID_QUESTION_GROUP AND E.UUID_QUESTION = F.UUID_QUESTION
WHERE E.REF_ID = 'PRE_TTD_PASANGAN'

SELECT A.FORM_NAME, C.IS_MANDATORY, C.RELEVANT_MANDATORY
FROM MS_FORM A with(nolock)
JOIN MS_FORMHISTORY B with(nolock) ON A.UUID_FORM = B.UUID_FORM AND B.FORM_VERSION = (SELECT MAX(FORM_VERSION) FROM MS_FORMHISTORY with(nolock) WHERE UUID_FORM = B.UUID_FORM)
JOIN MS_FORMQUESTIONSET C with(nolock) ON B.UUID_FORM = C.UUID_FORM AND B.UUID_FORM_HISTORY = C.UUID_FORM_HISTORY
JOIN MS_ANSWERTYPE D with(nolock) ON C.UUID_ANSWER_TYPE = D.UUID_ANSWER_TYPE
WHERE C.REF_ID = 'PRE_TTD_PASANGAN'

SELECT FORM_NAME, FORM_LAST_UPDATE
FROM MS_FORM A with(nolock)
WHERE FORM_NAME = 'FORM PRE SURVEY'


SELECT * FROM TBL_API_DASHBOARD tad 
WHERE tad.ORDER_NO_CAE ='POL000910944'