
/**
 *  Validasi Approval
 * Sit doc : https://docs.google.com/document/d/1KVSno_qhQZBxJIpso_zhHuuJakovIHV5eDDsoBdKuSw/edit?pli=1
 * Date: Nov 28, 2023
 */

--SETTINGAN 
SELECT parameter_id, PARAMETER_VALUE  FROM M_MKT_POLO_PARAMETER mmpp 
where PARAMETER_ID like '%angs%' or PARAMETER_ID like '%approval%' 

--DATA ELIGIBLE
SELECT 
	E.IS_PRE_APPROVAL, E.CAE_FINAL_RESULT,
	E.DISTRIBUTED_DT, E.ID_NO, E.AGRMNT_NO, E.PIPELINE_ID, E.IS_ACTIVE, E.BIRTH_PLACE, E.BIRTH_DT, E.SUB_ZIPCODE_RES, E.MONTHLY_INSTALLMENT, E.CUST_RATING CUST_RATING_RO,
	JSON_VALUE(E.CAE_RESULT,'$.result[10].score_category')CUST_RATING_CAE_RESULT,
	E.ASSET_TYPE, E.ITEM_DESCRIPTION, E.CONTRACT_STAT, E.MARITAL_STAT, E.HOME_STAT, E.ASSET_AGE
FROM WISE_STAGING..T_MKT_POLO_ELIGIBLE E WITH(NOLOCK)
WHERE E.IS_ACTIVE = 1 AND E.ID_NO = '3312173011720001'
AND AGRMNT_NO='1064120190500677'


-- DATA POLO
SELECT TOP 10 A.TASK_ID , A.DISTRIBUTED_DT, A.ID_NO, A.AGRMNT_NO, A.CUST_NAME, A.BIRTH_DT, A.BIRTH_PLACE, A.SUB_ZIPCODE_RES, A.HOUSE_OWNERSHIP, B.HOME_STAT, A.MONTHLY_INSTALMENT, A.ITEM_YEAR, (YEAR(GETDATE()) - A.ITEM_YEAR) AS ASSET_AGE, A.ASSET_TYPE 
FROM WISE_STAGING..T_MKT_POLO_ORDER_IN A WITH(NOLOCK)
JOIN WISE_STAGING..T_MKT_POLO_ORDER_IN_X B WITH(NOLOCK) ON  B.T_MKT_POLO_ORDER_IN_ID = A.T_MKT_POLO_ORDER_IN_ID
WHERE A.AGRMNT_NO = '1064120190500677'   
ORDER BY A.DISTRIBUTED_DT DESC

----UPDATE SCRIPT
DECLARE
@ID_NO VARCHAR(100), @AGRMNT_NO VARCHAR(100), @NEW_CUST_RATING VARCHAR(100)
SET @ID_NO = '3303147005820001' SET @AGRMNT_NO = '1379120191001447' SET @NEW_CUST_RATING = 'BAD'
BEGIN TRAN
SELECT 
	E.IS_PRE_APPROVAL, E.CAE_FINAL_RESULT,
	E.DISTRIBUTED_DT, E.AGRMNT_ID, E.AGRMNT_NO, E.CUST_NO,  E.ID_NO, E.CUST_NAME, E.BIRTH_DT, E.BIRTH_PLACE, E.SUB_ZIPCODE_RES, E.CAE_RESULT, JSON_VALUE(E.CAE_RESULT,'$.result[10].score_category') CUST_RATING_CAE,
	E.MONTHLY_INSTALLMENT, E.CUST_RATING, E.ASSET_TYPE, E.CONTRACT_STAT, E.MARITAL_STAT, E.HOME_STAT, E.ASSET_AGE
FROM WISE_STAGING..T_MKT_POLO_ELIGIBLE E WITH(NOLOCK)
WHERE E.IS_ACTIVE = 1 AND E.ID_NO = @ID_NO


		UPDATE E
		SET E.IS_PRE_APPROVAL = '1',
		E.CAE_FINAL_RESULT = 'PRE APPROVAL'  
		FROM WISE_STAGING..T_MKT_POLO_ELIGIBLE E WITH(NOLOCK)
		WHERE E.ID_NO = @ID_NO AND E.AGRMNT_NO = @AGRMNT_NO

		UPDATE E
		SET E.CAE_RESULT = (SELECT X.CAE_RESULT FROM WISE_STAGING..T_MKT_POLO_ELIGIBLE X WITH(NOLOCK) WHERE X.AGRMNT_NO = '800600047471') 
		FROM WISE_STAGING..T_MKT_POLO_ELIGIBLE E WITH(NOLOCK)
		WHERE E.ID_NO = @ID_NO AND E.AGRMNT_NO = @AGRMNT_NO

		UPDATE E
		SET E.CAE_RESULT = JSON_MODIFY(JSON_MODIFY(JSON_MODIFY(JSON_MODIFY(JSON_MODIFY(E.CAE_RESULT,'$.data.app_no', E.AGRMNT_ID), '$.data.cust_no', E.CUST_NO ), '$.data.nik', E.ID_NO ),'$.data.fullname', E.CUST_NAME ),'$.result[10].score_category', @NEW_CUST_RATING)
		FROM WISE_STAGING..T_MKT_POLO_ELIGIBLE E WITH(NOLOCK)
		WHERE E.ID_NO = @ID_NO AND E.AGRMNT_NO = @AGRMNT_NO

SELECT 
	E.IS_PRE_APPROVAL, E.CAE_FINAL_RESULT,
	E.DISTRIBUTED_DT, E.AGRMNT_ID, E.AGRMNT_NO, E.CUST_NO,  E.ID_NO, E.CUST_NAME, E.BIRTH_DT, E.BIRTH_PLACE, E.SUB_ZIPCODE_RES, E.CAE_RESULT, JSON_VALUE(E.CAE_RESULT,'$.result[10].score_category') CUST_RATING_CAE,
	E.MONTHLY_INSTALLMENT, E.CUST_RATING, E.ASSET_TYPE, E.CONTRACT_STAT, E.MARITAL_STAT, E.HOME_STAT, E.ASSET_AGE
FROM WISE_STAGING..T_MKT_POLO_ELIGIBLE E WITH(NOLOCK)
WHERE E.IS_ACTIVE = 1 AND E.ID_NO = @ID_NO
ROLLBACK TRAN