-- New script in DB IDE DASHB DEV 67.130.
-- Date: Aug 7, 2024
-- Time: 10:48:47 AM
/*Get Regional*/
SELECT OFFICE_REGION_CODE, OFFICE_REGION_NAME
	FROM M_REF_OFFICE_IDE
-- 	WHERE (OFFICE_REGION_CODE = 'ALL' OR OFFICE_REGION_CODE = regionCode)
	GROUP BY OFFICE_REGION_CODE, OFFICE_REGION_NAME;


/*Get Branch*/
call spIDE_GetListBranch (1)

SELECT OFFICE_REGION_NAME ,OFFICE_CODE, OFFICE_NAME
    FROM M_REF_OFFICE_IDE MROI
    WHERE (MROI.OFFICE_REGION_CODE = 'ALL' OR MROI.OFFICE_REGION_CODE = 1 )
    GROUP BY OFFICE_REGION_NAME,OFFICE_CODE, OFFICE_NAME
    ORDER BY OFFICE_NAME ASC limit 12
    
/*Get Branch Head*/ 
	SELECT DISTINCT  MRO.OFFICE_REGION_NAME ,ME.OFFICE_NAME ,EMP_NAME_SPV as BRANCH_HEAD_NAME, EMP_NAME ,ME.JOB_TITLE_NAME, ME.IS_ACTIVE 
	FROM M_EMPLOYEE_IDE ME
	JOIN M_REF_OFFICE_IDE MRO ON MRO.OFFICE_CODE = ME.OFFICE_CODE
	WHERE (MRO.OFFICE_REGION_NAME = 'ALL' OR MRO.OFFICE_REGION_NAME = "JATENG SELATAN")
	AND MRO.OFFICE_NAME = "BANYUMAS"
    ORDER BY BRANCH_HEAD_NAME ASC;
   
 
	SELECT MRO.OFFICE_REGION_NAME, MRO.OFFICE_NAME , COUNT(1)TOTAL
	FROM M_EMPLOYEE_IDE ME
	JOIN M_REF_OFFICE_IDE MRO ON MRO.OFFICE_CODE = ME.OFFICE_CODE
-- 	WHERE (MRO.OFFICE_REGION_NAME = 'ALL' OR MRO.OFFICE_REGION_NAME = "JABODEBEK")
-- 	AND MRO.OFFICE_NAME = "JAKARTA TIMUR"
	GROUP BY MRO.OFFICE_REGION_NAME, MRO.OFFICE_NAME 
    ORDER BY TOTAL ASC;
    
/*Get Staff*/
SELECT CONCAT("ALL") as id, CONCAT("ALL") as label
    UNION
    SELECT id, label
    FROM (
        SELECT DISTINCT ME.EMP_NO as id, ME.EMP_NAME AS label
        FROM M_EMPLOYEE_IDE ME
        JOIN M_REF_OFFICE_IDE MRO ON MRO.OFFICE_CODE = ME.OFFICE_CODE
        WHERE (MRO.OFFICE_REGION_NAME = 'ALL' OR MRO.OFFICE_REGION_NAME = "JATENG SELATAN")
        GROUP BY ME.EMP_NO, ME.EMP_NAME
        ORDER BY label ASC
    ) AS result; 
   
/* Availibiliy Team*/
   SELECT ME.EMP_NO, ME.EMP_NAME, TCA.IS_ACTIVE_IDE, TCA.DATE_NON_ACTIVE 
	FROM (
		SELECT DISTINCT ME.EMP_NO, ME.EMP_NAME
		FROM M_EMPLOYEE_IDE ME
		JOIN M_REF_OFFICE_IDE MRO ON MRO.OFFICE_CODE = ME.OFFICE_CODE
		WHERE 1=1
-- 		and ('ALL' = SpvName OR COALESCE(ME.EMP_NAME_SPV, '') = IF(SpvName = 'null', '', SpvName))
-- 		AND ('ALL' = EmpName OR ME.EMP_NAME = EmpName)
-- 		AND ('ALL' = RegionName OR MRO.OFFICE_REGION_NAME = RegionName)
-- 		AND ('ALL' = OfficeName OR MRO.OFFICE_NAME = OfficeName)
		and ME.EMP_NAME_SPV='ROFIQ HIDAYAT'
-- 		and ME.EMP_NAME='185170391'
	) AS ME
	LEFT JOIN T_CDE_ACTIVE TCA ON TCA.EMP_NO = ME.EMP_NO 
	WHERE 1
-- 	GROUP BY ME.EMP_NO, ME.EMP_NAME, TCA.IS_ACTIVE_IDE
	
/*Average SLA by CDE*/ 
SELECT ME.EMP_NAME,TTI.SLA_CDE-- ROUND(AVG(TTI.SLA_CDE), 2) AS AVG_SLA
    FROM T_TRANSACTION_IDE TTI
	JOIN (
		SELECT DISTINCT ME.EMP_NO, ME.EMP_NAME
		FROM M_EMPLOYEE_IDE ME
		JOIN M_REF_OFFICE_IDE MRO ON MRO.OFFICE_CODE = ME.OFFICE_CODE
		WHERE 1=1 
		and ME.EMP_NO='028111322'
	) AS ME ON ME.EMP_NO = TTI.EMP_NO_CDE
	WHERE 1
    AND CAST(TTI.DTM_CRT AS DATE) = '2024-08-21'
    GROUP BY ME.EMP_NAME
    
    
      SELECT 'ON SCHEDULE' CASE_SAMPLE
    , tti.T_TRACK_IDE_ID ID, tti.TASK_ID, tti.REGION_CODE,mroi.OFFICE_REGION_NAME , tti.OFFICE_CODE,mroi.OFFICE_NAME , tti.EMP_NO_CDE 
    , tti.EMP_NO_APPROVAL_ON_WOM 
    , tti.ORDER_NO , tti.WISE_STAT , tti.WISE_STAT_DT , tti.MAPPING_WISE_STAT 
    , tti.MSS_STAT , tti.MSS_STAT_DT , tti.MAPPING_MSS_STAT 
    , tti.HOLD_STAT 
    , (select SLA_START 
    		from T_SLA_CDE cde 
    		where cde.task_id = tti.TASK_ID
    		and T_SLA_CDE_ID = (select MIN(T_SLA_CDE_ID) from T_SLA_CDE where task_id = tti.TASK_ID )
    		) SLA_START_CDE
	, (select SLA_END 
    		from T_SLA_CDE cde 
    		where cde.task_id = tti.TASK_ID
    		and T_SLA_CDE_ID = (select MAX(T_SLA_CDE_ID) from T_SLA_CDE where task_id = tti.TASK_ID )
    		) SLA_END_CDE
    , tti.SLA_CDE
    , (select SLA_START 
    		from T_SLA_APPROVAL_ON_WOM cde 
    		where cde.task_id = tti.TASK_ID
    		and T_SLA_APPROVAL_ON_WOM_ID = (select MIN(T_SLA_APPROVAL_ON_WOM_ID) from T_SLA_APPROVAL_ON_WOM where task_id = tti.TASK_ID )
    		) SLA_START_ON_WOM
	, (select SLA_END 
    		from T_SLA_APPROVAL_ON_WOM cde 
    		where cde.task_id = tti.TASK_ID
    		and T_SLA_APPROVAL_ON_WOM_ID = (select MAX(T_SLA_APPROVAL_ON_WOM_ID) from T_SLA_APPROVAL_ON_WOM where task_id = tti.TASK_ID )
    		) SLA_END_ON_WOM
	, tti.SLA_APPROVAL_ON_WOM 
    , tti.USR_CRT , tti.USR_UPD 
    FROM T_TRANSACTION_IDE tti
    left join M_REF_OFFICE_IDE mroi on mroi.OFFICE_CODE =tti.OFFICE_CODE 
    where 1=1
--     and tti.TASK_ID ='POL2024082114'
    and CAST(tti.DTM_CRT AS DATE) = '2024-08-21'
    and tti.OFFICE_CODE ="5221"
    and tti.REGION_CODE = 5
--     and CDE.EMP_NAME_SPV ='BAMBANG PURWANTO' 
    order by tti.T_TRACK_IDE_ID desc
     
    
    select * 
    from M_PARAMETERIZE_CHART mpc 
    where code ='008'
    
    update M_PARAMETERIZE_CHART 
    set VALUE_MIN =0,VALUE_MAX =25
    where code ='008' and id=20
    
 0	25
26	45
    
    select DATE_SLA, HOUR_START_SLA , HOUR_END_SLA 
    from M_UPLOAD_SLA_DAY musd 
    where CAST(DATE_SLA AS DATE) = '2024-08-21'
    
    select EMP_NO_CDE , SLA_CDE ##ROUND(AVG(TTI.SLA_CDE), 2) AS AVG_SLA
    from T_TRANSACTION_IDE ide 
    where CAST(DTM_CRT AS DATE) = '2024-08-21'
    and EMP_NO_CDE ='028220526'
    
 select * from T_TRANSACTION_IDE ide where EMP_NO_CDE ='028220526' and SLA_CDE =171
    
028220526	ROFIQ HIDAYAT
028111322	NUR SIGIT AJIANTO
000140702	HASTOMO NUGROHO
        
    select * from T_TRANSACTION_IDE tti 
    where  CAST(tti.DTM_CRT AS DATE) = '2024-08-21'
    and exists (select 1 from T_SLA_CDE where T_TRACK_IDE_ID = tti.T_TRACK_IDE_ID)
    and CUST_NAME ='Niqs'
    
--     delete  from T_TRANSACTION_IDE  
    where  CAST(DTM_CRT AS DATE) = '2024-08-21'
    and exists (select 1 from T_SLA_CDE where T_TRACK_IDE_ID = T_TRACK_IDE_ID)
    and task_id='POL2024082113'
    and CUST_NAME ='Niqs'
    
    select * from T_SLA_APPROVAL_ON_WOM tsaow where tsaow.T_TRACK_IDE_ID ='580'
    
    select * from T_SLA_CDE tsc 
    where T_TRACK_IDE_ID =600
    
    select * from MAPPING_TASK_MSS mtm 
    
    select * from MAPPING_TASK_WISE mtw 
	
SELECT DISTINCT ME.EMP_NO, ME.EMP_NAME, TCA.IS_ACTIVE_IDE , TCA.DTM_CRT , TCA.USR_CRT  , TCA.DTM_UPD , TCA.USR_UPD 

select  DISTINCT ME.OFFICE_CODE , ME.OFFICE_NAME, ME.OFFICE_SHORT_NAME , ME.EMP_NO, ME.EMP_NAME  , ME.EMP_NO_SPV, ME.EMP_NAME_SPV 
	,TCA.* 
	FROM M_EMPLOYEE_IDE ME
	JOIN M_REF_OFFICE_IDE MRO ON MRO.OFFICE_CODE = ME.OFFICE_CODE
	LEFT JOIN T_CDE_ACTIVE TCA ON TCA.EMP_NO = ME.EMP_NO 
	WHERE 1=1   	
   	AND MRO.OFFICE_REGION_NAME = "JATENG SELATAN"
	AND MRO.OFFICE_NAME = "BANYUMAS"
-- 	and ME.EMP_NAME_SPV='BAMBANG PURWANTO'	
	
		SELECT * from T_CDE_ACTIVE where EMP_NO ='000222946'
		
		select * from M_EMPLOYEE_IDE mei
		where mei.EMP_NO ='028111322'
		and mei.EMP_NAME_SPV='BAMBANG PURWANTO'	
		
		select * from T_SLA_CDE tsc 
		
 SELECT DISTINCT  MRO.OFFICE_REGION_NAME ,ME.OFFICE_NAME , EMP_NO_SPV ,EMP_NAME_SPV as BRANCH_HEAD_NAME, EMP_NO ,EMP_NAME ,ME.JOB_TITLE_NAME, ME.IS_ACTIVE 
	FROM M_EMPLOYEE_IDE ME
	left JOIN M_REF_OFFICE_IDE MRO ON MRO.OFFICE_CODE = ME.OFFICE_CODE
-- 	left join T_CDE_ACTIVE tca on tca.EMP_NO =ME.EMP_NO 
	WHERE 1=1
	AND MRO.OFFICE_REGION_NAME = "JATENG SELATAN"
	AND MRO.OFFICE_NAME = "BANYUMAS"
	AND ME.EMP_NAME_SPV ='BAMBANG PURWANTO'
    ORDER BY EMP_NAME ASC;

   select distinct EMP_NAME 
   FROM M_EMPLOYEE_IDE ME
	left JOIN M_REF_OFFICE_IDE MRO ON MRO.OFFICE_CODE = ME.OFFICE_CODE
	WHERE 1=1
-- 	AND MRO.OFFICE_REGION_NAME = "JATENG SELATAN"
-- 	AND MRO.OFFICE_NAME = "BANYUMAS"
	AND ME.EMP_NAME_SPV ='BAMBANG PURWANTO'
    ORDER BY EMP_NAME ASC;
   
   
select * from T_TRANSACTION_IDE tti
where cast(LAST_STATUS_DT as date) ='2024-08-15'
and MAPPING_MSS_STAT ='Antrian'

select * from T_TRANSACTION_IDE tti
where cast(LAST_STATUS_DT as date) ='2024-08-16'

select * from M_UPLOAD_SLA_DAY musd 

select MAPPING_MSS_STAT , cast(LAST_STATUS_DT as date) LAST_STATUS_DT,  count(1)Total
from T_TRANSACTION_IDE tti 
group by MAPPING_MSS_STAT , cast(LAST_STATUS_DT as date) 

select MAPPING_MSS_STAT ,  cast(DTM_CRT as date) DTM_CRT , count(1)Total
from T_TRANSACTION_IDE tti 
group by MAPPING_MSS_STAT ,  cast(DTM_CRT as date)
   
select * from MAPPING_TASK_MSS mtm 
select * from MAPPING_TASK_WISE mtw 
   
select * from T_TRANSACTION_IDE order by T_TRACK_IDE_ID desc limit 1

   
select OFFICE_CODE,OFFICE_NAME , OFFICE_REGION_CODE , OFFICE_REGION_NAME 
from M_REF_OFFICE_IDE
where OFFICE_NAME ='BANYUMAS' 

select * from M_EMPLOYEE_IDE where OFFICE_NAME ='BANYUMAS'

    
SELECT 
CONVERT(A.DTM_CRT,DATE) TANGGAL,
sum((CASE WHEN A.MAPPING_WISE_STAT ='CANCEL' THEN 1 ELSE 0 END )) AS 'CANCEL' 
FROM T_TRANSACTION_IDE A 
LEFT JOIN M_REF_OFFICE_IDE B ON B.OFFICE_CODE = A.OFFICE_CODE
WHERE  B.OFFICE_REGION_NAME LIKE '%jabodebek%'
and (A.MAPPING_WISE_STAT !='' and A.MAPPING_WISE_STAT NOT IN ('ANTRIAN NAP')) 
GROUP BY CONVERT(A.DTM_CRT,DATE)


select A.TASK_ID, A.ORDER_NO, A.MSS_STAT, A.MSS_STAT_DT, A.MAPPING_MSS_STAT
, A.WISE_STAT, A.WISE_STAT_DT, A.MAPPING_WISE_STAT 
, A.REGION_CODE , B.OFFICE_REGION_NAME , A.OFFICE_CODE  , B.OFFICE_NAME 
, A.EMP_NO_CDE,CDE.EMP_NAME , A.EMP_NO_APPROVAL_ON_WOM , A.CUST_NO , A.CUST_NAME 
, A.DTM_CRT , A.DTM_UPD , A.USR_CRT , A.USR_UPD 
FROM T_TRANSACTION_IDE A 
JOIN M_REF_OFFICE_IDE B on A.OFFICE_CODE =B.OFFICE_CODE 
left join M_EMPLOYEE_IDE CDE on A.EMP_NO_CDE =CDE.EMP_NO 
left join M_EMPLOYEE_IDE WOM on A.EMP_NO_CDE =WOM.EMP_NO
where CAST(A.DTM_CRT as DATE)=  '2024-08-20'
and CDE.EMP_Name like '%RIVAL%'


update T_TRANSACTION_IDE A 
set A.DTM_CRT ='2024-08-22 07:01:36'
,WISE_STAT_DT ='2024-08-22 07:01:36'
, MSS_STAT_DT = '2024-08-22 07:01:36'
where CAST(A.DTM_CRT as DATE)=  '2024-08-21'


 SELECT ME.EMP_NAME, COUNT(TTI.MAPPING_MSS_STAT) AS TOTAL_COUNT
    FROM T_TRANSACTION_IDE TTI
	JOIN (
		SELECT DISTINCT ME.EMP_NO, ME.EMP_NAME
		FROM M_EMPLOYEE_IDE ME
		JOIN M_REF_OFFICE_IDE MRO ON MRO.OFFICE_CODE = ME.OFFICE_CODE
-- 		WHERE ('ALL' = SpvName OR COALESCE(ME.EMP_NAME_SPV, '') = IF(SpvName = 'null', '', SpvName))
-- 		AND ('ALL' = EmpName OR ME.EMP_NAME = EmpName)
-- 		AND ('ALL' = RegionName OR MRO.OFFICE_REGION_NAME = RegionName)
-- 		AND ('ALL' = OfficeName OR MRO.OFFICE_NAME = OfficeName)
	) AS ME ON ME.EMP_NO = TTI.EMP_NO_APPROVAL_ON_WOM
    WHERE TTI.MAPPING_MSS_STAT = 'done'
    GROUP BY ME.EMP_NAME

select * from M_EMPLOYEE_IDE
where EMP_NO ='000222946'


/*data Wise*/
select wise.* 
,case when (wise.mapping_wise_stat = "NAP" or wise.mapping_wise_stat = "PREPARATION") and ifnull(wise.HOLD_STAT,'') <> "HOLD" then "Outstanding Wise" end outstanding_flag
from (
	select 'Wise' scope,dta.mapping_wise_stat mapping_wise_stat, cast(dta.DTM_CRT as date ) application_dt
	, dta.EMP_NAME_CDE,dta.HOLD_STAT, count(1) total 
	from (
	select A.TASK_ID, A.ORDER_NO, A.WISE_STAT, A.WISE_STAT_DT, A.MAPPING_WISE_STAT , A.HOLD_STAT
	, A.REGION_CODE , B.OFFICE_REGION_NAME , A.OFFICE_CODE  , B.OFFICE_NAME 
	, A.EMP_NO_CDE, CDE.EMP_NAME EMP_NAME_CDE , A.EMP_NO_APPROVAL_ON_WOM , MSS.EMP_NAME EMP_NAME_MSS
	, A.CUST_NO , A.CUST_NAME 
	, A.DTM_CRT , A.DTM_UPD , A.USR_CRT , A.USR_UPD 
	FROM T_TRANSACTION_IDE A 
	JOIN M_REF_OFFICE_IDE B on A.OFFICE_CODE =B.OFFICE_CODE 
	left join (select distinct emp_no, emp_name from M_EMPLOYEE_IDE  
					) CDE on A.EMP_NO_CDE =CDE.EMP_NO 
	left join (select distinct emp_no, emp_name from M_EMPLOYEE_IDE  
					) MSS on A.EMP_NO_APPROVAL_ON_WOM =MSS.EMP_NO 
	where CAST(A.DTM_CRT as DATE)=  '2024-08-19'
	and A.USR_CRT  = 'WISe'
	) dta 
	group by dta.mapping_wise_stat, cast(dta.DTM_CRT as date ),dta.EMP_NAME_CDE,dta.HOLD_STAT
	order by dta.EMP_NAME_CDE
)wise
-- where hold_stat ='HOLD'

/*data MSS*/
select 'MSS' scope, dta.mapping_mss_stat mapping_mss_stat, cast(dta.DTM_CRT as date ) application_dt, dta.EMP_NAME_MSS emp_name, count(1) total 
from (
select  A.ORDER_NO, A.MSS_STAT, A.MSS_STAT_DT, A.MAPPING_MSS_STAT 
, A.REGION_CODE , B.OFFICE_REGION_NAME , A.OFFICE_CODE  , B.OFFICE_NAME 
, A.EMP_NO_CDE, CDE.EMP_NAME EMP_NAME_CDE , A.EMP_NO_APPROVAL_ON_WOM , MSS.EMP_NAME EMP_NAME_MSS 
, A.CUST_NO , A.CUST_NAME 
, A.DTM_CRT , A.DTM_UPD , A.USR_CRT , A.USR_UPD 
FROM T_TRANSACTION_IDE A 
JOIN M_REF_OFFICE_IDE B on A.OFFICE_CODE =B.OFFICE_CODE 
left join (select distinct emp_no, emp_name from M_EMPLOYEE_IDE  
				) CDE on A.EMP_NO_CDE =CDE.EMP_NO 
left join (select distinct emp_no, emp_name from M_EMPLOYEE_IDE  
				) MSS on A.EMP_NO_APPROVAL_ON_WOM =MSS.EMP_NO 
where CAST(A.DTM_CRT as DATE)=  '2024-08-19'
and A.USR_CRT='MSS'
) dta 
group by dta.mapping_mss_stat, cast(dta.DTM_CRT as date ), dta.EMP_NAME_MSS
order by dta.EMP_NAME_MSS


select * from T_TRANSACTION_IDE A 
where CAST(A.DTM_CRT as DATE)=  '2024-08-19' 
and USR_CRT ='wise'
and A.EMP_NO_CDE ='ROFIQ HIDAYAT'

order by T_TRACK_IDE_ID desc

select * from MAPPING_TASK_MSS mtm 

select * from MAPPING_TASK_WISE mtw 

SELECT TTI.T_TRACK_IDE_ID
		FROM T_TRANSACTION_IDE TTI
		JOIN (
			SELECT DISTINCT ME.EMP_NO, ME.EMP_NAME
			FROM M_EMPLOYEE_IDE ME
			JOIN M_REF_OFFICE_IDE MRO ON MRO.OFFICE_CODE = ME.OFFICE_CODE
			WHERE  CAST(ME.DTM_CRT as DATE)=  '2024-08-19'
		) AS ME ON ME.EMP_NO = TTI.EMP_NO_CDE
		WHERE TTI.MAPPING_WISE_STAT IN ('ANTRIAN NEW', 'ANTRIAN NAP') 
		GROUP BY TTI.T_TRACK_IDE_ID


SELECT 
B.OFFICE_REGION_NAME ,B.OFFICE_NAME , A.*
FROM T_TRANSACTION_IDE A 
LEFT JOIN M_REF_OFFICE_IDE B ON B.OFFICE_CODE = A.OFFICE_CODE
WHERE  B.OFFICE_REGION_NAME LIKE '%jabodebek%'
and (A.MAPPING_WISE_STAT !='' and A.MAPPING_WISE_STAT NOT IN ('ANTRIAN NAP')) 

GROUP BY CONVERT(A.DTM_CRT,DATE)

select * from T_TRANSACTION_IDE
order by DTM_CRT desc limit 10

select * from MAPPING_TASK_MSS mtm 

select * from T_TRACK_IDE

select * from T_CDE_ACTIVE tca 

select tsc.TASK_ID , tsc.SLA_START , tsc.SLA_END ,SLA_CDE,SLA_APPROVAL_ON_WOM 
from T_TRANSACTION_IDE ide 
left join T_SLA_CDE tsc on ide.T_TRACK_IDE_ID = tsc.T_TRACK_IDE_ID 

select * from T_HOLD_CDE thc 
select * from T_SLA_CDE tsc 

SELECT B.OFFICE_NAME , A.*
FROM
(	SELECT
	A.OFFICE_CODE,
	SUM(CASE WHEN A.MAPPING_WISE_STAT in ('DONE') THEN 1 ELSE 0 END) AS DONE,
	SUM(CASE WHEN A.MAPPING_WISE_STAT in ('CANCEL') THEN 1 ELSE 0 END) AS CANCEL,
	SUM(CASE WHEN (A.MAPPING_WISE_STAT in ('PREPARATION') AND A.HOLD_STAT IN ('RESUME','')) THEN 1 ELSE 0 END) AS PREPARATION,
	SUM(CASE WHEN (A.MAPPING_WISE_STAT in ('NAP') AND (A.HOLD_STAT IN ('RESUME','') OR A.HOLD_STAT IS NULL)) THEN 1 ELSE 0 END) AS NAP,
	SUM(CASE WHEN (A.MAPPING_WISE_STAT in ('PREPARATION','NAP') AND A.HOLD_STAT IN ('HOLD')) THEN 1 ELSE 0 END) AS HOLD,
	SUM(CASE WHEN (A.MAPPING_WISE_STAT in ('PREPARATION','NAP') AND A.HOLD_STAT IN ('HOLD') AND A.FEED_MKT IN('YES')) THEN 1 ELSE 0 END) AS FEED_MKT,
	COUNT(*) AS TOTAL_APP
	FROM T_TRANSACTION_IDE A 
	WHERE
	(CONVERT(A.DTM_CRT,DATE) BETWEEN '2024-08-01' AND '2024-08-01')
	and (A.MAPPING_WISE_STAT !='' and A.MAPPING_WISE_STAT is not null) 
	GROUP BY 1
) AS A
CROSS JOIN M_REF_OFFICE_IDE B -- ON B.OFFICE_CODE = A.OFFICE_CODE
WHERE B.OFFICE_REGION_NAME LIKE '%jabodebek%'
order by B.OFFICE_NAME desc

select * from M_REF_OFFICE_IDE

/*
 *  { CALL dbide.spIDE_GetListBranch(:regionCode) }
 * */

select ttih.* #--T_TRACK_IDE_HIST_ID HISTORY_ID,A.*
FROM T_TRANSACTION_IDE A
join T_TRANSACTION_IDE_HIST ttih on  A.T_TRACK_IDE_ID =ttih.T_TRACK_IDE_ID
where A.TASK_ID ='POL000910944'

SELECT * FROM T_TRANSACTION_IDE tti WHERE tti.TASK_ID ='POL000910944'

SELECT * FROM MAPPING_TASK_WISE mtw 